In [70]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

In [43]:
dados = {
    "animal": [
        "Cachorro",
        "Gato",
        "Porco",
        "Passaro",
        "Cachorro",
        "Gato",
        "Porco",
        "Passaro",
    ],
    "late": [1, 0, 0, 0, 1, 0, 1, 0],
    "tem_pelo": [1, 1, 1, 0, 1, 1, 0, 0],
    "4_patas": [1, 1, 1, 0, 1, 1, 1, 0],
    "voa": [0, 0, 0, 1, 0, 0, 0, 1],
}

In [44]:
df = pd.DataFrame(dados, columns=dados.keys())

In [45]:
df

animal  late  tem_pelo  4_patas  voa
0  Cachorro     1         1        1    0
1      Gato     0         1        1    0
2     Porco     0         1        1    0
3   Passaro     0         0        0    1
4  Cachorro     1         1        1    0
5      Gato     0         1        1    0
6     Porco     1         0        1    0
7   Passaro     0         0        0    1

In [46]:
novo_animal = [[1, 1, 1, 0]]

In [47]:
dic = {"Cachorro": 0, "Gato": 1, "Porco": 2, "Passaro": 3}

In [48]:
df.animal = df.animal.replace(dic)

In [49]:
df

animal  late  tem_pelo  4_patas  voa
0       0     1         1        1    0
1       1     0         1        1    0
2       2     0         1        1    0
3       3     0         0        0    1
4       0     1         1        1    0
5       1     0         1        1    0
6       2     1         0        1    0
7       3     0         0        0    1

In [50]:
X = df.drop(columns=["animal"])
y = df["animal"]

In [51]:
X

late  tem_pelo  4_patas  voa
0     1         1        1    0
1     0         1        1    0
2     0         1        1    0
3     0         0        0    1
4     1         1        1    0
5     0         1        1    0
6     1         0        1    0
7     0         0        0    1

In [52]:
y

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
Name: animal, dtype: int64

In [56]:
desvio_padrao_scaler = StandardScaler()

In [57]:
x_scaled = desvio_padrao_scaler.fit_transform(X)
x_scaled

array([[ 1.29099445,  0.77459667,  0.57735027, -0.57735027],
       [-0.77459667,  0.77459667,  0.57735027, -0.57735027],
       [-0.77459667,  0.77459667,  0.57735027, -0.57735027],
       [-0.77459667, -1.29099445, -1.73205081,  1.73205081],
       [ 1.29099445,  0.77459667,  0.57735027, -0.57735027],
       [-0.77459667,  0.77459667,  0.57735027, -0.57735027],
       [ 1.29099445, -1.29099445,  0.57735027, -0.57735027],
       [-0.77459667, -1.29099445, -1.73205081,  1.73205081]])

In [58]:
x_scaled[0]

array([ 1.29099445,  0.77459667,  0.57735027, -0.57735027])

In [60]:
novo_animal_scaled = desvio_padrao_scaler.transform(
    pd.DataFrame(novo_animal, columns=X.columns)
)
novo_animal_scaled

array([[ 1.29099445,  0.77459667,  0.57735027, -0.57735027]])

In [61]:
a = novo_animal
b = x_scaled[0]

In [62]:
a - b

array([[-0.29099445,  0.22540333,  0.42264973,  0.57735027]])

In [63]:
np.square(a - b)

array([[0.08467777, 0.05080666, 0.17863279, 0.33333333]])

In [64]:
np.sum(np.square(a - b))

0.6474505589995039

In [66]:
np.sqrt(0.6474505589995039)

0.8046431252421808

In [69]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.30)

In [71]:
knc = KNeighborsClassifier(metric="euclidean")

In [72]:
knc.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean')

In [73]:
y_pred = knc.predict(x_test)

In [74]:
y_pred

array([2, 2, 2])